### ISSUE TITLE
Can't browse multiple pages

### ISSUE THREAD

**Issue by francois** [sbellity/futon4mongo#2]
From the list of collections (homepage), I changed to 100 collections, then clicked the last collection's name.  I ended up with the following backtraces:

```
RuntimeError - Unknown options [{:skip=>0}]:
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/mongodb-mongo-0.14.1/lib/mongo/collection.rb:115:in `find'
 ./serve:118:in `GET /:database/:collection/_all_docs'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `route'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/showexceptions.rb:24:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/methodoverride.rb:24:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/commonlogger.rb:18:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/content_length.rb:13:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/chunked.rb:15:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/handler/thin.rb:14:in `run'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:946:in `run!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/main.rb:25
 ./serve:280
RuntimeError: Unknown options [{:skip=>0}]
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/mongodb-mongo-0.14.1/lib/mongo/collection.rb:115:in `find'
        ./serve:118:in `GET /:database/:collection/_all_docs'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `route'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/showexceptions.rb:24:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/methodoverride.rb:24:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/commonlogger.rb:18:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/content_length.rb:13:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/chunked.rb:15:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/handler/thin.rb:14:in `run'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:946:in `run!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/main.rb:25
        ./serve:280
127.0.0.1 - - [20/May/2010 10:18:04] "GET /adgear_staging%2Fcampaign_212/_all_docs?limit=11 HTTP/1.1" 500 111200 0.1569
GetKey : 
GetKey : _design/
GetKey : _design0
RuntimeError - Unknown options [{:skip=>0}]:
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/mongodb-mongo-0.14.1/lib/mongo/collection.rb:115:in `find'
 ./serve:118:in `GET /:database/:collection/_all_docs'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `route'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/showexceptions.rb:24:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/methodoverride.rb:24:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/commonlogger.rb:18:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/content_length.rb:13:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/chunked.rb:15:in `call'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/handler/thin.rb:14:in `run'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:946:in `run!'
 /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/main.rb:25
 ./serve:280
RuntimeError: Unknown options [{:skip=>0}]
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/mongodb-mongo-0.14.1/lib/mongo/collection.rb:115:in `find'
        ./serve:118:in `GET /:database/:collection/_all_docs'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `route'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/showexceptions.rb:24:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/methodoverride.rb:24:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/commonlogger.rb:18:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/content_length.rb:13:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/chunked.rb:15:in `call'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib/rack/handler/thin.rb:14:in `run'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/base.rb:946:in `run!'
        /Users/francois/.rvm/gems/ruby-1.8.7-p249/gems/sinatra-1.0/lib/sinatra/main.rb:25
        ./serve:280
```

**Comment by sbellity** [comment]
Your version you mongo driver is too old and does not support the "skip" option. You should try to update to the latest version.
