### ISSUE TITLE
rack 1.2.2

### ISSUE THREAD

**Issue by koroboku** [sbellity/futon4mongo#4]
hello!
thanks for the very useful application for mongodb!
i have installed rails with mongo_mapper and get error when tryin rackup:

<pre>
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:31:in `block in setup': You have already activated rack 1.2.2, but your Gemfile requires rack 1.2.1. Consider using bundle exec. (Gem::LoadError)
    from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12:in `block in each'
    from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:17:in `setup'
    from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler.rb:115:in `setup'
    from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.0.12/lib/bundler.rb:120:in `require'
    from config.ru:5:in `block in <main>'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/builder.rb:46:in `instance_eval'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/builder.rb:46:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1:in `<main>'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/builder.rb:35:in `eval'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/builder.rb:35:in `parse_file'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/server.rb:162:in `app'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/server.rb:248:in `wrapped_app'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/server.rb:213:in `start'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/lib/rack/server.rb:100:in `start'
    from /usr/lib/ruby/gems/1.9.1/gems/rack-1.2.2/bin/rackup:4:in `<top (required)>'
    from /usr/bin/rackup:19:in `load'
    from /usr/bin/rackup:19:in `<main>'
</pre>

ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-linux]
i can provide more info if it is necessary

**Comment by koroboku** [comment]
i think this issue can be closed. this error disappeared when i removed rack 1.2.2 and install 1.2.1 instead
